version: '2'
services:
 postgres:
   image: postgres:9.6
   ports:
     - "5432:5432"
   environment:
     - POSTGRES_DB=wpattern_multi_tenancy
     - POSTGRES_USER=user
     - POSTGRES_PASSWORD=password
     - MAX_CONNECTIONS=300
   volumes:
     - ./scripts:/docker-entrypoint-initdb.d
