spring:
  application:
    name: wpattern-multi-tenancy
  profiles:
    active: postgresql

tenant:
  default: public

server:
  contextPath: /
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wpattern_multi_tenancy
    username: user
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

logging:
  file: build/wpattern-multi-tenancy.log
  level:
    br.com.wpattern: DEBUG
    br.com.zup: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
